
<?php
require_once __DIR__ . '/config/database.php'; $db=getDB();
$q=trim($_GET['q']??'');$location=trim($_GET['location']??'');$type=trim($_GET['type']??'');
$where=["o.status='active'"];$params=[];
if($q!==''){ $where[]="(o.title LIKE ? OR o.description LIKE ? OR o.organization LIKE ? OR o.location LIKE ?)";$x="%$q%";array_push($params,$x,$x,$x,$x);}
if($location!==''){$where[]="o.location LIKE ?";$params[]="%$location%";} if($type!==''){$where[]="o.opportunity_type=?";$params[]=$type;}
$st=$db->prepare("SELECT o.*,u.full_name owner_name FROM opportunities o LEFT JOIN users u ON u.id=o.owner_id WHERE ".implode(" AND ",$where)." ORDER BY CASE WHEN o.deadline IS NULL OR o.deadline='' THEN 1 ELSE 0 END, date(o.deadline) ASC, o.id DESC");$st->execute($params);$items=$st->fetchAll(PDO::FETCH_ASSOC);
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Opportunities • MALTWEB</title><link rel="stylesheet" href="assets/css/maltweb.css"></head>
<body><header class="site-header"><div class="container nav"><a class="brand" href="index.php">MALTWEB</a><nav><a href="search.php">Discover</a><a href="events.php">Events</a><a class="active" href="opportunities.php">Opportunities</a><a href="auth/login.php">Login</a></nav></div></header>
<main class="container" style="padding:42px 20px"><div class="section-heading"><div><span class="eyebrow">OPEN DOORS</span><h1>Opportunities</h1><p>Jobs, scholarships, training, internships, funding and more.</p></div><a class="btn" href="opportunity/create.php">+ Post opportunity</a></div>
<form class="search-panel" method="get"><input name="q" value="<?=htmlspecialchars($q)?>" placeholder="Search opportunities..."><input name="location" value="<?=htmlspecialchars($location)?>" placeholder="Area / location"><select name="type"><option value="">All types</option><?php foreach(['Job','Scholarship','Training','Internship','Tender','Volunteer','Funding','Other'] as $x):?><option value="<?=$x?>" <?=$type===$x?'selected':''?>><?=$x?></option><?php endforeach;?></select><button class="btn" type="submit">Search</button></form>
<div class="card-grid"><?php foreach($items as $o):?><article class="card"><span class="tag"><?=htmlspecialchars($o['opportunity_type'])?></span><h2><?=htmlspecialchars($o['title'])?></h2><?php if($o['organization']):?><p><strong><?=htmlspecialchars($o['organization'])?></strong></p><?php endif;?><p><?=nl2br(htmlspecialchars($o['description']))?></p><p><strong>Location:</strong> <?=htmlspecialchars($o['location']?:'Not specified')?></p><?php if($o['deadline']):?><p><strong>Deadline:</strong> <?=htmlspecialchars($o['deadline'])?></p><?php endif;?><?php if($o['contact_email']):?><a href="mailto:<?=htmlspecialchars($o['contact_email'])?>">Email</a><?php endif;?> <?php if($o['website']):?><a href="<?=htmlspecialchars($o['website'])?>" target="_blank" rel="noopener">Website</a><?php endif;?></article><?php endforeach;?></div>
<?php if(!$items):?><div class="empty-state"><h2>No opportunities found</h2><p>Try another search or post an opportunity.</p></div><?php endif;?></main></body></html>
